version: '3.3'

services:
  db:
    image: mysql:5.6
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ms-db
      MYSQL_USER: ms-user
      MYSQL_PASSWORD: drupal
     
      
  web:
      build: .
      depends_on:
        - db
      
      ports:
        - "8000:80"
      restart: always
      
volumes:
     db-data: 
    
